// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRP7UnBxPpAYbUtm14bF3UtIFQ2d1_rZM',
    appId: '1:68814527816:web:77c06d5be6159c5ad5277d',
    messagingSenderId: '68814527816',
    projectId: 'sporti-b4f92',
    authDomain: 'sporti-b4f92.firebaseapp.com',
    databaseURL: 'https://sporti-b4f92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sporti-b4f92.firebasestorage.app',
    measurementId: 'G-LGMM8YPF38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrOnaAlTqX87u_woZs7Zte8ukB5aS_zU',
    appId: '1:68814527816:android:6b29b64eba807b17d5277d',
    messagingSenderId: '68814527816',
    projectId: 'sporti-b4f92',
    databaseURL: 'https://sporti-b4f92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sporti-b4f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZTaXqUKJfOY56UMiWbBE8El5finkWjA',
    appId: '1:68814527816:ios:34c3c8caef63b47dd5277d',
    messagingSenderId: '68814527816',
    projectId: 'sporti-b4f92',
    databaseURL: 'https://sporti-b4f92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sporti-b4f92.firebasestorage.app',
    iosBundleId: 'com.example.sportitionClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZTaXqUKJfOY56UMiWbBE8El5finkWjA',
    appId: '1:68814527816:ios:34c3c8caef63b47dd5277d',
    messagingSenderId: '68814527816',
    projectId: 'sporti-b4f92',
    databaseURL: 'https://sporti-b4f92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sporti-b4f92.firebasestorage.app',
    iosBundleId: 'com.example.sportitionClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC24ab7qAawjhPEYtbfQpWHfFynf9diW64',
    appId: '1:68814527816:web:0f53cc86a94db8fed5277d',
    messagingSenderId: '68814527816',
    projectId: 'sporti-b4f92',
    authDomain: 'sporti-b4f92.firebaseapp.com',
    databaseURL: 'https://sporti-b4f92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sporti-b4f92.firebasestorage.app',
    measurementId: 'G-HL90FFL0KE',
  );

}